---
device_name: /dev/nvme1n1
device_number: 1
pv_name: "{{ device_name }}p1"
vg_name: vg_blockchain
lv_name: lv_blockchain
validator_hostname: validator-shardnet-dev
blockchain_data_dir: /root/.near
config_url: https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore-deploy/shardnet/config.json
version_tag: 68bfa84ed1455f891032434d37ccad696e91e4f5
NEAR_ENV: shardnet

node_account_id: inc4
node_public_key: 
node_secret_key: 

validator_account_id: inc4.factory.shardnet.near
validator_public_key: 
validator_secret_key: 
